ALTER TABLE users MODIFY uuid binary(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), 1));
ALTER TABLE ugroups MODIFY uuid binary(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), 1));
ALTER TABLE transactions MODIFY uuid binary(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), 1));
